import { createAudioPlayer, setAudioModeAsync, AudioPlayer } from 'expo-audio';
import { Channel, channelVolume } from './mixer';
// Type-only: the audio layer reads the boon taxonomy but must never pull the
// catalog (and its icon/palette imports) into the sound module at runtime.
import type { BoonKind } from './pickups';

/**
 * Tiny imperative sound board. Each effect gets its own player so rapid
 * retriggers just seek back to 0.
 *
 * The board is organised by WHAT AN EVENT MEANS, not by what plays it:
 *   • pop1..pop5 — the kill-pitch ladder, pre-pitched, read by playKill.
 *   • shot_*     — what the player did.
 *   • pickup_*   — what the player got. Always rises.
 *   • sys_*      — what the game is reporting about state.
 *   • ui_*       — what the SHELL is saying back to a finger. The only board
 *                  that plays outside a run, and the only one carried on the
 *                  `ui` mixer channel.
 *
 * The pops are the one family still using pre-pitched samples; the newer
 * boards use one sample transposed at playback (see playPitched), so adding a
 * member costs no asset. Coin and heart used to borrow pop2 and pop4, which
 * meant a pickup was indistinguishable from a x3 kill — the ladder is a
 * readout, and nothing else may speak with its voice.
 */
const sources = {
  pop1: require('../../assets/sounds/pop1.wav'),
  pop2: require('../../assets/sounds/pop2.wav'),
  pop3: require('../../assets/sounds/pop3.wav'),
  pop4: require('../../assets/sounds/pop4.wav'),
  pop5: require('../../assets/sounds/pop5.wav'),
  buzz: require('../../assets/sounds/buzz.wav'),
  whoosh: require('../../assets/sounds/whoosh.wav'),
  gameover: require('../../assets/sounds/gameover.wav'),
  // The player's own gun, one voice per WEAPON. The default 'single' has no
  // entry here and no sound at all — see SHOT_VOICE. Generated by
  // scripts/make-shot-sfx.mjs — retune there, not by hand.
  shot_double: require('../../assets/sounds/shot_double.wav'),
  shot_laser: require('../../assets/sounds/shot_laser.wav'),
  shot_bomb: require('../../assets/sounds/shot_bomb.wav'),
  shot_homing: require('../../assets/sounds/shot_homing.wav'),
  // Pickups, one voice per drop FAMILY rather than per kind. Generated by
  // scripts/make-pickup-sfx.mjs — see playPickup() for how a kind picks its
  // voice and its pitch.
  pickup_coin: require('../../assets/sounds/pickup_coin.wav'),
  pickup_vital: require('../../assets/sounds/pickup_vital.wav'),
  pickup_shield: require('../../assets/sounds/pickup_shield.wav'),
  pickup_power: require('../../assets/sounds/pickup_power.wav'),
  pickup_control: require('../../assets/sounds/pickup_control.wav'),
  pickup_charge: require('../../assets/sounds/pickup_charge.wav'),
  pickup_gift: require('../../assets/sounds/pickup_gift.wav'),
  // System events — the game reporting STATE. Generated by
  // scripts/make-system-sfx.mjs; see playSystem().
  sys_arm: require('../../assets/sounds/sys_arm.wav'),
  sys_block: require('../../assets/sounds/sys_block.wav'),
  sys_chain: require('../../assets/sounds/sys_chain.wav'),
  sys_special: require('../../assets/sounds/sys_special.wav'),
  sys_wave: require('../../assets/sounds/sys_wave.wav'),
  // Interface — the shell answering a press. Generated by
  // scripts/make-ui-sfx.mjs; see playUi() for how an event picks its voice.
  ui_tap: require('../../assets/sounds/ui_tap.wav'),
  ui_confirm: require('../../assets/sounds/ui_confirm.wav'),
  ui_deny: require('../../assets/sounds/ui_deny.wav'),
} as const;

type SoundName = keyof typeof sources;

/**
 * Every effect, in declaration order.
 *
 * Exported so tests can assert against the real board rather than a hardcoded
 * count — adding a sound should not fail an unrelated test.
 */
export const SOUND_NAMES = Object.keys(sources) as SoundName[];

const players: Partial<Record<SoundName, AudioPlayer>> = {};
let ready = false;

export async function initSounds(): Promise<void> {
  if (ready) return;
  try {
    // Play even when the iPhone mute switch is on — it's a game.
    await setAudioModeAsync({ playsInSilentMode: true });
  } catch {
    // No audio session is annoying but never fatal. Leave `ready` false so a
    // later init retries.
    return;
  }
  // Per-asset, NOT one try around the loop.
  //
  // The loop used to share a single catch, which made one unloadable asset
  // silence every effect declared after it — and because players are created
  // in declaration order, that failed silently and asymmetrically: the pops
  // are first, so the game would still sound its kills while everything else
  // went quiet, which reads as "the new sounds don't work" rather than as "one
  // asset is broken". Isolating each keeps the rest of the board alive and
  // says which one failed.
  (Object.keys(sources) as SoundName[]).forEach((name) => {
    try {
      players[name] = createAudioPlayer(sources[name]);
    } catch (e) {
      if (__DEV__) console.warn(`[sounds] could not load "${name}" — that effect will be silent`, e);
    }
  });
  ready = true;

  // Not under Jest. The probe exists to catch a player that never finishes
  // DECODING on a device; under test every player is a double that cannot
  // decode or fail, so it can only ever report success — into a worker that
  // has usually been torn down by the time it fires ("Cannot log after tests
  // are done"). Noise in a suite people are meant to read is a real cost, and
  // this costs the probe nothing where it does its job.
  if (__DEV__ && process.env.NODE_ENV !== 'test') {
    // Construction is synchronous; DECODING is not. createAudioPlayer returns a
    // player immediately and loads in the background, so a player that never
    // finishes loading throws nothing, logs nothing, and simply refuses to make
    // a sound for the rest of the session. That is the one audio failure with
    // no symptom other than silence, so it is worth one timer at boot to name
    // it. Reports only what is still unloaded well after init.
    const probe = setTimeout(() => {
      // Strictly `false`, not falsy: a player that does not report the field
      // at all has not told us it failed, and treating silence-about-loading
      // as a load failure would cry wolf on every test double.
      const dead = (Object.keys(sources) as SoundName[]).filter((n) => players[n]?.isLoaded === false);
      if (dead.length) {
        console.warn(
          `[sounds] ${dead.length}/${SOUND_NAMES.length} players never finished loading: ${dead.join(', ')}`
        );
      } else {
        console.log(`[sounds] all ${SOUND_NAMES.length} players loaded`);
      }
    }, 4000);
    // Node keeps the event loop alive for a pending timer, so under Jest this
    // one held the worker open past the end of the run ("failed to exit
    // gracefully"). unref() exists on Node's timer handle and not on React
    // Native's, hence the check rather than a straight call.
    (probe as unknown as { unref?: () => void })?.unref?.();
  }
}

/**
 * Fire one effect on the `sfx` channel.
 *
 * `volume` is the event's own tuned level and stays the source of truth for
 * how the board is balanced; the player's channel gain only scales it.
 */
export function play(name: SoundName, volume = 1): void {
  fire(name, volume * channelVolume('sfx'));
}

/**
 * Poke one player, after the channel gain has already been applied.
 *
 * Returns BEFORE touching the player at zero. A muted channel should cost
 * nothing, and a seekTo/play pair per kill is real work to do for silence.
 */
function fire(name: SoundName, volume: number): void {
  if (volume <= 0) return;
  const p = players[name];
  if (!p) return;
  try {
    p.volume = volume;
    p.seekTo(0);
    p.play();
  } catch {
    // Ignore playback hiccups mid-game.
  }
}

/** Collect pop at one of 5 rising pitches (clamped), chosen by the caller. */
export function playPop(pitch: number): void {
  const idx = Math.max(1, Math.min(5, pitch));
  play(`pop${idx}` as SoundName, 0.9);
}

/**
 * A kill, pitched by the chain multiplier.
 *
 * The five pop samples are already pre-pitched, and until now every kill played
 * pop3 regardless — so the asset was on disk doing nothing. Mapping pitch to the
 * chain turns the kill sound into a running readout of how well you are playing,
 * which is one of the cheapest and most satisfying feedback loops in the genre.
 */
export function playKill(multiplier: number): void {
  // ×1 → pop1 … ×10 → pop5, so the ladder spans the whole multiplier range.
  const step = Math.round(1 + ((Math.max(1, multiplier) - 1) / 9) * 4);
  playPop(step);
}

// Graze ticks. Throttled hard: in a dense pattern a player grazes many times a
// second, and one sound per graze would be an unlistenable rattle that also
// buried the kill pitch ladder. Played much quieter than a kill so the two read
// as different events despite sharing the sample set — a purpose-made dry tick
// would separate them better.
let lastGrazeAt = 0;
const GRAZE_MIN_GAP_MS = 110;

export function playGraze(multiplier: number): void {
  const now = Date.now();
  if (now - lastGrazeAt < GRAZE_MIN_GAP_MS) return;
  lastGrazeAt = now;
  const step = Math.max(1, Math.min(5, 1 + Math.floor((Math.max(1, multiplier) - 1) / 2)));
  play(`pop${step}` as SoundName, 0.22);
}

// The player's own gun. Throttled because at a maxed fire rate the interval
// drops near 0.19s and every shot re-triggering a shared player would both cut
// itself off constantly and turn into an unpleasant rattle.
let lastShotAt = 0;
const SHOT_MIN_GAP_MS = 80;

/**
 * Which voice each weapon fires with — and which one deliberately has none.
 *
 * 'single' is ABSENT on purpose, and its absence is the design. It is the gun
 * you hold for most of a run and it fires several times a second, so it is the
 * only weapon whose sound a player would hear tens of thousands of times; at
 * that repetition there is no such thing as a sound that stays welcome. Its
 * silence also does something no mixing could: it makes a picked-up gun
 * announce itself, because grabbing one audibly changes the soundtrack of your
 * own firing. Silence is the baseline the rest of the weapon board reads
 * against.
 *
 * Each of the other four says what its shot DOES: two barrels beat against
 * each other, the beam holds its pitch, the lob is blunt and driven, and the
 * homing round is the only shot in the game that rises — because it is not
 * departing, it is seeking.
 */
const SHOT_VOICE: Record<string, SoundName> = {
  double: 'shot_double',
  laser: 'shot_laser',
  bomb: 'shot_bomb',
  homing: 'shot_homing',
};

/**
 * The player's primary action.
 *
 * Was a borrowed `whoosh` at volume 0.1 — inaudible, and the most repeated
 * sound in the game. Now a purpose-made blip per weapon family (see
 * scripts/make-shot-sfx.mjs).
 *
 * Kept deliberately quiet: this fires several times a second and sits UNDER the
 * kill-pitch ladder, which is the sound that actually carries information.
 */
export function playShot(gun?: string): void {
  const voice = SHOT_VOICE[gun ?? ''];
  // No voice means the default gun, which fires silently by design. Bail
  // BEFORE the throttle so a silent shot never consumes the window that the
  // next real shot needs.
  if (!voice) return;
  const now = Date.now();
  if (now - lastShotAt < SHOT_MIN_GAP_MS) return;
  lastShotAt = now;
  // Slight volume jitter so a sustained stream doesn't fatigue as one flat tone.
  play(voice, 0.3 + Math.random() * 0.06);
}

/** Reset the throttle — used when a run starts so the first shot always sounds. */
export function resetShotThrottle(): void {
  lastShotAt = 0;
}

/**
 * Everything the player can collect.
 *
 * The three card kinds are listed alongside BoonKind because as far as audio
 * is concerned they are the same event — "you picked something up" — and
 * splitting them would mean two mechanisms doing one job.
 */
export type PickupKind = BoonKind | 'heart' | 'coin' | 'gift';

/**
 * Which family voice each pickup speaks with.
 *
 * These MIRROR the colour families in pickups.ts on purpose. A drop is already
 * categorised visually by hue ("families share a hue so the drop reads at a
 * glance"); making audio agree means the player learns one taxonomy instead of
 * two, and a mismatch between a boon's colour and its voice is a bug — see
 * sounds.pickups.test.ts, which asserts the two agree.
 */
const PICKUP_VOICE: Record<PickupKind, SoundName> = {
  // Economy — gold
  coin: 'pickup_coin',
  magnet: 'pickup_coin',
  doubleCoins: 'pickup_coin',
  luckyDrop: 'pickup_coin',
  // Vital — red
  heart: 'pickup_vital',
  repair: 'pickup_vital',
  extraHeart: 'pickup_vital',
  // Defensive — plasma
  shield: 'pickup_shield',
  // Offensive — amber
  damageBoost: 'pickup_power',
  fireBoost: 'pickup_power',
  nuke: 'pickup_power',
  bombPack: 'pickup_power',
  // Control — violet
  freeze: 'pickup_control',
  slowmo: 'pickup_control',
  // Charge — energy
  energy: 'pickup_charge',
  // The weapon drop stands alone: it is the most consequential pickup in the
  // game and gets the only three-note fanfare.
  gift: 'pickup_gift',
};

/**
 * Semitone offsets available within a family.
 *
 * A pentatonic set (root, second, minor third, fourth, fifth) rather than a
 * chromatic one, so ANY two members of a family are consonant with each other.
 * That matters because the offsets are assigned automatically: with chromatic
 * steps a future boon could land a semitone from its sibling and sound like a
 * mistake, and nobody would think to check.
 */
const PENTATONIC = [0, 2, 3, 5, 7];

/**
 * Per-kind pitch offsets.
 *
 * Unpinned kinds derive their offset from their own name (see below), which
 * keeps an offset stable no matter what else is added or reordered. Pins exist
 * for two reasons:
 *
 *  - The three CARD kinds are pinned to 0. They are the canonical members of
 *    their families and should speak their voice untransposed.
 *  - COLLISIONS are pinned by hand. Deriving from a hash cannot guarantee that
 *    two members of the same family land on different slots, and three pairs
 *    did collide: doubleCoins/luckyDrop, heart/extraHeart, fireBoost/bombPack.
 *    Resolving that automatically would mean a new boon could silently shift a
 *    sibling's pitch, which is worse than an explicit line here.
 *
 * If you add a boon and it collides, sounds.pickups.test.ts fails and names
 * the pair — pin the newcomer to a free slot from PENTATONIC.
 */
const PICKUP_PITCH: Partial<Record<PickupKind, number>> = {
  coin: 0,
  heart: 0,
  gift: 0,
  // Collision pins. Each takes a slot its family had free.
  luckyDrop: 5, // would have hit doubleCoins' +2
  extraHeart: 3, // would have hit heart's +0
  bombPack: 5, // would have hit fireBoost's +2
};

/** FNV-1a. Same function as the generators use, for the same reason: a stable
 *  per-name value, so an offset never depends on declaration order. */
function hashKind(str: string): number {
  let h = 0x811c9dc5;
  for (let i = 0; i < str.length; i++) {
    h ^= str.charCodeAt(i);
    h = Math.imul(h, 0x01000193);
  }
  return h >>> 0;
}

/** Semitones this kind is transposed by within its family voice. */
export function pickupSemitones(kind: PickupKind): number {
  return PICKUP_PITCH[kind] ?? PENTATONIC[hashKind(kind) % PENTATONIC.length];
}

/**
 * A pickup, spoken by its family voice at its own pitch.
 *
 * Transposed at PLAYBACK rather than baked into a sample per kind. Sixteen
 * pre-pitched files would be sixteen assets and sixteen AudioPlayers for
 * information the ear cannot use anyway, and every new boon would need another
 * one. This way a boon costs no new asset and no new player — which is the
 * extensibility rule pickups.ts already set for itself.
 *
 * `shouldCorrectPitch` must be false: correction is the default behaviour for
 * a rate change, and with it on the sound would play faster at the SAME pitch,
 * which is the one thing we do not want.
 */
export function playPickup(kind: PickupKind, volume = 0.85): void {
  playPitched(PICKUP_VOICE[kind], volume, pickupSemitones(kind));
}

/**
 * Play one voice transposed by `semitones`.
 *
 * Shared by the pickup and system boards, which both use one sample per family
 * and separate members by pitch.
 *
 * `shouldCorrectPitch` must be false: correction is the DEFAULT for a rate
 * change, and with it on the sound plays faster at the same pitch — which is
 * the one thing we do not want, and which would silently collapse every family
 * to a single note.
 */
function playPitched(
  name: SoundName,
  volume: number,
  semitones: number,
  channel: Channel = 'sfx'
): void {
  const level = volume * channelVolume(channel);
  if (level <= 0) return;
  const p = players[name];
  if (!p) return;
  try {
    p.volume = level;
    // Transposition is BEST EFFORT, and deliberately in its own try.
    //
    // These two setters are the least portable thing the sound board touches:
    // support for a rate change without pitch correction varies by platform
    // and by player state. Sharing a try with the play() call below meant that
    // if either setter threw, the sound never played at all — trading a voice
    // that would have been merely untransposed for total silence. The pitch is
    // a nicety; the sound is the requirement.
    try {
      p.shouldCorrectPitch = false;
      p.playbackRate = Math.pow(2, semitones / 12);
    } catch {
      // Family speaks at its baked pitch. Still the right voice.
    }
    p.seekTo(0);
    p.play();
  } catch {
    // Ignore playback hiccups mid-game.
  }
}

/**
 * Everything the game reports about STATE, as opposed to what the player did
 * (shots) or got (pickups).
 *
 * All seven of these shared a single `ding` separated only by volume, which is
 * not a distinguishing dimension — a quieter version of a sound is the same
 * sound. The costly one was `block`: a defensive save and a coin pickup are
 * different enough events that sharing a voice loses real information in the
 * middle of a fight.
 */
export type SystemEvent =
  | 'armed'
  | 'overcharged'
  | 'chain'
  | 'block'
  | 'reflect'
  | 'special'
  | 'specialOver'
  | 'waveClear';

/**
 * Voice, pitch and level per system event.
 *
 * Paired events share a sample and separate by pitch, because they ARE the
 * same event at two intensities: armed/overcharged is one meter filling,
 * block/reflect is one shell doing its job. Two unrelated samples would say
 * they were unrelated things.
 *
 * Levels are carried here rather than at the call site so the whole board can
 * be balanced by reading one table. `reflect` is the quiet one by a distance:
 * it can fire several times inside one enemy burst, and at absorb's level it
 * would be a rattle.
 */
const SYSTEM_VOICE: Record<SystemEvent, { name: SoundName; semis: number; volume: number }> = {
  armed: { name: 'sys_arm', semis: 0, volume: 0.55 },
  overcharged: { name: 'sys_arm', semis: 5, volume: 0.75 },
  chain: { name: 'sys_chain', semis: 0, volume: 0.6 },
  block: { name: 'sys_block', semis: 0, volume: 0.6 },
  reflect: { name: 'sys_block', semis: 5, volume: 0.3 },
  special: { name: 'sys_special', semis: 0, volume: 0.9 },
  specialOver: { name: 'sys_special', semis: 3, volume: 1 },
  waveClear: { name: 'sys_wave', semis: 0, volume: 0.85 },
};

/** Semitones a system event is transposed by. Exported for the guard test. */
export function systemSemitones(event: SystemEvent): number {
  return SYSTEM_VOICE[event].semis;
}

export function playSystem(event: SystemEvent): void {
  const v = SYSTEM_VOICE[event];
  playPitched(v.name, v.volume, v.semis);
}

/**
 * Semitones a block is transposed by, given the charges LEFT after it.
 *
 * A falling ladder: a full shield answers at pitch, and each spent charge
 * drops the answer a whole tone, so the last block before a shatter is the
 * lowest and flattest sound the shell makes. Same information the rim's arcs
 * carry, routed to the ear — which matters because during a dense pattern the
 * player's eyes are on the bullets, not on their own hull.
 *
 * Exported as a pure function so the ladder can be asserted without a player.
 */
export function blockSemitones(left: number, max: number): number {
  const spent = Math.max(0, Math.min(max, max - left));
  // Returned explicitly rather than as `-STEP * 0`, which is negative zero —
  // harmless to the playback rate, but it makes an untouched shield compare
  // unequal to "no transposition" and that is a confusing thing to debug.
  return spent === 0 ? 0 : -BLOCK_STEP_SEMIS * spent;
}

/** Whole tone per charge spent. */
const BLOCK_STEP_SEMIS = 2;

/** A shell absorbing a hit, pitched by what the shield has left afterwards. */
export function playBlock(left: number, max: number): void {
  const v = SYSTEM_VOICE.block;
  playPitched(v.name, v.volume, v.semis + blockSemitones(left, max));
}


// --- Interface ---------------------------------------------------------------

/**
 * What a press MEANT, not which button was pressed.
 *
 * Naming these by intent rather than by widget is what stops the board growing
 * a member per screen. A shop row, a rail button and a modal dismiss are three
 * widgets and only two intents, and every future screen is already covered by
 * one of these five.
 */
export type UiEvent =
  /** Any forward press: a destination opened, a choice made. */
  | 'tap'
  /** Any backward press: back, close, dismiss. */
  | 'back'
  /** Something was switched: a tab, an equipped hull, a sky. */
  | 'select'
  /** A transaction landed: bought, upgraded, claimed. */
  | 'confirm'
  /** Refused: can't afford it, it's locked, it's maxed. */
  | 'deny';

/**
 * Voice, pitch and level per interface event.
 *
 * Three of the five share `ui_tap` and separate by pitch, for the reason the
 * system board gives: they are one action in different directions. Forward is
 * the untransposed root, back is a fifth BELOW it, and select sits a fourth
 * above — so navigation reads as movement along one axis rather than as three
 * unrelated noises.
 *
 * Levels live here so the whole shell can be balanced by reading one table.
 * `tap` is the quietest thing in the game on purpose: it plays on every press
 * of every screen, and it is furniture, not information.
 */
const UI_VOICE: Record<UiEvent, { name: SoundName; semis: number; volume: number }> = {
  tap: { name: 'ui_tap', semis: 0, volume: 0.5 },
  back: { name: 'ui_tap', semis: -7, volume: 0.42 },
  select: { name: 'ui_tap', semis: 5, volume: 0.55 },
  confirm: { name: 'ui_confirm', semis: 0, volume: 0.7 },
  deny: { name: 'ui_deny', semis: 0, volume: 0.55 },
};

/** Semitones an interface event is transposed by. Exported for the guard test. */
export function uiSemitones(event: UiEvent): number {
  return UI_VOICE[event].semis;
}

// A press is rate-limited by the finger, but not reliably: nested pressables
// and a fast double-tap can both fire twice inside a few ms, and two clicks
// that close enough together read as a rattle rather than as two presses.
// Much tighter than the shot throttle — this must never swallow a real second
// press, only a duplicate of the first.
let lastUiAt = 0;
const UI_MIN_GAP_MS = 40;

/**
 * The shell answering a finger.
 *
 * Carried on the `ui` channel rather than `sfx`, which is the whole reason
 * this is a separate entry point: a player who wants a quiet interface but a
 * loud game — or the reverse — can have it. Muting the channel makes this an
 * early return in playPitched, so a silenced menu costs nothing at all.
 */
export function playUi(event: UiEvent): void {
  const now = Date.now();
  if (now - lastUiAt < UI_MIN_GAP_MS) return;
  lastUiAt = now;
  const v = UI_VOICE[event];
  playPitched(v.name, v.volume, v.semis, 'ui');
}

/** Reset the interface throttle. Testing seam. */
export function resetUiThrottle(): void {
  lastUiAt = 0;
}
