import { createAudioPlayer, setAudioModeAsync, AudioPlayer } from 'expo-audio';

/**
 * Tiny imperative sound board. Each effect gets its own player so rapid
 * retriggers just seek back to 0. The pops are 5 pre-pitched samples, so
 * callers pick a pitch to distinguish what just happened (a coin from a
 * heart from a kill).
 */
const sources = {
  pop1: require('../../assets/sounds/pop1.wav'),
  pop2: require('../../assets/sounds/pop2.wav'),
  pop3: require('../../assets/sounds/pop3.wav'),
  pop4: require('../../assets/sounds/pop4.wav'),
  pop5: require('../../assets/sounds/pop5.wav'),
  buzz: require('../../assets/sounds/buzz.wav'),
  ding: require('../../assets/sounds/ding.wav'),
  whoosh: require('../../assets/sounds/whoosh.wav'),
  gameover: require('../../assets/sounds/gameover.wav'),
  // The player's own gun, one voice per weapon family. Generated by
  // scripts/make-shot-sfx.mjs — retune there, not by hand.
  shot: require('../../assets/sounds/shot.wav'),
  shot_laser: require('../../assets/sounds/shot_laser.wav'),
  shot_bomb: require('../../assets/sounds/shot_bomb.wav'),
} as const;

type SoundName = keyof typeof sources;

/**
 * Every effect, in declaration order.
 *
 * Exported so tests can assert against the real board rather than a hardcoded
 * count — adding a sound should not fail an unrelated test.
 */
export const SOUND_NAMES = Object.keys(sources) as SoundName[];

const players: Partial<Record<SoundName, AudioPlayer>> = {};
let ready = false;

export async function initSounds(): Promise<void> {
  if (ready) return;
  try {
    // Play even when the iPhone mute switch is on — it's a game.
    await setAudioModeAsync({ playsInSilentMode: true });
    (Object.keys(sources) as SoundName[]).forEach((name) => {
      players[name] = createAudioPlayer(sources[name]);
    });
    ready = true;
  } catch {
    // No audio is annoying but never fatal.
  }
}

export function play(name: SoundName, volume = 1): void {
  const p = players[name];
  if (!p) return;
  try {
    p.volume = volume;
    p.seekTo(0);
    p.play();
  } catch {
    // Ignore playback hiccups mid-game.
  }
}

/** Collect pop at one of 5 rising pitches (clamped), chosen by the caller. */
export function playPop(pitch: number): void {
  const idx = Math.max(1, Math.min(5, pitch));
  play(`pop${idx}` as SoundName, 0.9);
}

/**
 * A kill, pitched by the chain multiplier.
 *
 * The five pop samples are already pre-pitched, and until now every kill played
 * pop3 regardless — so the asset was on disk doing nothing. Mapping pitch to the
 * chain turns the kill sound into a running readout of how well you are playing,
 * which is one of the cheapest and most satisfying feedback loops in the genre.
 */
export function playKill(multiplier: number): void {
  // ×1 → pop1 … ×10 → pop5, so the ladder spans the whole multiplier range.
  const step = Math.round(1 + ((Math.max(1, multiplier) - 1) / 9) * 4);
  playPop(step);
}

// Graze ticks. Throttled hard: in a dense pattern a player grazes many times a
// second, and one sound per graze would be an unlistenable rattle that also
// buried the kill pitch ladder. Played much quieter than a kill so the two read
// as different events despite sharing the sample set — a purpose-made dry tick
// would separate them better.
let lastGrazeAt = 0;
const GRAZE_MIN_GAP_MS = 110;

export function playGraze(multiplier: number): void {
  const now = Date.now();
  if (now - lastGrazeAt < GRAZE_MIN_GAP_MS) return;
  lastGrazeAt = now;
  const step = Math.max(1, Math.min(5, 1 + Math.floor((Math.max(1, multiplier) - 1) / 2)));
  play(`pop${step}` as SoundName, 0.22);
}

// The player's own gun. Throttled because at a maxed fire rate the interval
// drops near 0.19s and every shot re-triggering a shared player would both cut
// itself off constantly and turn into an unpleasant rattle.
let lastShotAt = 0;
const SHOT_MIN_GAP_MS = 80;

/**
 * Which voice each weapon fires with.
 *
 * The guns already looked different and sounded identical, so weapon variety
 * was carried entirely by the art. Three voices from one family is enough to
 * make a swap audible without turning the mix into a zoo: bolts blip, the beam
 * holds its pitch, a lob thumps. Anything not listed uses the default bolt.
 */
const SHOT_VOICE: Record<string, SoundName> = {
  laser: 'shot_laser',
  bomb: 'shot_bomb',
};

/**
 * The player's primary action.
 *
 * Was a borrowed `whoosh` at volume 0.1 — inaudible, and the most repeated
 * sound in the game. Now a purpose-made blip per weapon family (see
 * scripts/make-shot-sfx.mjs).
 *
 * Kept deliberately quiet: this fires several times a second and sits UNDER the
 * kill-pitch ladder, which is the sound that actually carries information.
 */
export function playShot(gun?: string): void {
  const now = Date.now();
  if (now - lastShotAt < SHOT_MIN_GAP_MS) return;
  lastShotAt = now;
  // Slight volume jitter so a sustained stream doesn't fatigue as one flat tone.
  play(SHOT_VOICE[gun ?? ''] ?? 'shot', 0.3 + Math.random() * 0.06);
}

/** Reset the throttle — used when a run starts so the first shot always sounds. */
export function resetShotThrottle(): void {
  lastShotAt = 0;
}
